export const GET_MOVIES_BY_SEARCH = "GET_MOVIES_BY_SEARCH";
export const SAVE_SEARCH_KEYWORD = "SAVE_SEARCH_KEYWORD";
export const GET_MOVIES = "GET_MOVIES";
export const SAVE_FILTER_VALUE = "SAVE_FILTER_VALUE";
export const SAVE_CURRENT_PAGE = "SAVE_CURRENT_PAGE";
export const CHANGE_FAVORITE_MOVIES = "CHANGE_FAVORITE_MOVIES";
