export const GET_MOVIES_BY_SEARCH = "GET_MOVIES_BY_SEARCH";
export const GET_MOVIES = "GET_MOVIES";
export const CHANGE_FAVORITE_MOVIES = "CHANGE_FAVORITE_MOVIES";
export const GET_FAVORITE_MOVIES = "GET_FAVORITE_MOVIES";
